"""empty message

Revision ID: ba6b98d7a141
Revises: d685fe3f0b00
Create Date: 2025-06-01 22:08:23.480377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6b98d7a141'
down_revision: Union[str, None] = 'd685fe3f0b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('locked_money_amount', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('locked_instrument_amount', sa.Integer(), nullable=True))
    op.alter_column('orders', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'locked_instrument_amount')
    op.drop_column('orders', 'locked_money_amount')
    # ### end Alembic commands ###
