"""empty message

Revision ID: e4f2f0c3f265
Revises: bc52ac8181fe
Create Date: 2025-06-05 23:55:52.661898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f2f0c3f265'
down_revision: Union[str, None] = 'bc52ac8181fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'locked_amount')
    op.add_column('orders', sa.Column('locked_amount', sa.Integer(), nullable=False))
    op.drop_column('orders', 'locked_money')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('locked_money', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'locked_amount')
    op.add_column('balances', sa.Column('locked_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
