"""empty message

Revision ID: 5533b0a0842e
Revises: ba6b98d7a141
Create Date: 2025-06-01 22:46:15.010220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5533b0a0842e'
down_revision: Union[str, None] = 'ba6b98d7a141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'filled',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'filled',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
