"""empty message

Revision ID: d139b714fb52
Revises: e4f2f0c3f265
Create Date: 2025-06-06 17:57:36.830404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd139b714fb52'
down_revision: Union[str, None] = 'e4f2f0c3f265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('locked_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'locked_amount')
    # ### end Alembic commands ###
